name: Cache usage example

on:
  push:

jobs:
  producer-job:
    run-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Run simply command
        run: |
          ls -la