name: Cache usage example

on:
  push:

jobs:
  cache-producer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Output to cache
        run: |
          mkdir cache
          echo "hello cache" >> output.txt
          ls cache

      - name: Cache output
        id: cache-output
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-out-file
  
  cache-hit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Prime Numbers
        if: steps.cache-outputs.outputs.cache-hit != 'true'
        run: |
          ls cache